"""
taxonomy -- the catalog of things a human can build in Blender.

This is the enumeration backbone. Every entry becomes a catalog item with an
id, a display name, the construction recipes it needs, its real-world size class
and a build status, which is what `scripts/catalog.py` serves and what the
scoring loop iterates over.

Coverage rule: a domain is listed when the class of thing exists in the world
AND has a stable 3D form that a person could recognise from one render. Each
item names ONE concrete object -- "Coffee Mug", not "Drinkware" -- because the
quality gate is per-object: somebody has to be able to tell at a glance whether
that specific object is right.

SIZE_MM is the real bounding extent, and it drives the studio rig, so an entry
without a plausible size is not finished.

RECIPES reference bkit helpers: box rounded_box cylinder cone tube sphere torus
arc_torus lathe loft extrude_profile gear thread perforated_panel plus the
general tools mesh_from, bevel, boolean, mirror, array, subdivide.
"""
from collections import OrderedDict

SIZE = OrderedDict([
    ("micro", (0.2, 5)),
    ("tiny", (5, 30)),
    ("small", (30, 150)),
    ("medium", (150, 600)),
    ("large", (600, 3000)),
    ("huge", (3000, 40000)),
])

# (domain_id, domain_title, reference_note, [(item_id, display, size, [recipes]), ...])
DOMAINS = [
    ("kitchen", "Kitchen & Dining", "ceramic, glass, steel, wood; lathes and thin walls",
     [
         ("coffee_mug", "Coffee Mug", "small", ["lathe", "arc_torus"]),
         ("dinner_plate", "Dinner Plate", "medium", ["lathe"]),
         ("bowl", "Cereal Bowl", "small", ["lathe"]),
         ("teapot", "Teapot", "small", ["lathe", "arc_torus"]),
         ("kettle", "Stove Kettle", "small", ["lathe", "cylinder"]),
         ("frying_pan", "Frying Pan", "medium", ["lathe", "extrude_profile"]),
         ("saucepan", "Saucepan", "small", ["lathe"]),
         ("knife", "Kitchen Knife", "medium", ["extrude_profile", "bevel"]),
         ("fork", "Fork", "medium", ["box", "array"]),
         ("spoon", "Spoon", "medium", ["lathe", "subdivide"]),
         ("chopping_board", "Chopping Board", "medium", ["rounded_box"]),
         ("rolling_pin", "Rolling Pin", "medium", ["lathe", "arc_torus"]),
         ("pepper_mill", "Pepper Mill", "medium", ["lathe"]),
         ("wine_glass", "Wine Glass", "small", ["lathe"]),
         ("carafe", "Water Carafe", "medium", ["lathe", "arc_torus"]),
         ("cutlery_set", "Cutlery Set", "small", ["box", "array"]),
         ("chopsticks", "Chopsticks", "medium", ["taper", "bevel"]),
         ("corkscrew", "Corkscrew", "small", ["thread", "helix"]),
     ]),
    ("furniture", "Furniture", "lofted sections, legs, upholstery; proportions carry the object",
     [
         ("dining_chair", "Dining Chair", "medium", ["loft", "box", "bevel"]),
         ("office_chair", "Office Chair", "medium", ["loft", "cylinder", "box"]),
         ("armchair", "Armchair", "large", ["loft", "rounded_box"]),
         ("sofa", "Three-Seat Sofa", "large", ["rounded_box", "loft"]),
         ("coffee_table", "Coffee Table", "large", ["rounded_box", "cylinder"]),
         ("dining_table", "Dining Table", "large", ["rounded_box", "box"]),
         ("bookshelf", "Bookshelf", "large", ["box", "array"]),
         ("wardrobe", "Wardrobe", "large", ["box", "bevel"]),
         ("bed", "Double Bed", "large", ["rounded_box", "loft"]),
         ("nightstand", "Nightstand", "medium", ["box", "cylinder"]),
         ("desk", "Writing Desk", "large", ["rounded_box", "box"]),
         ("bookshelf_ladder", "Ladder Shelf", "large", ["cylinder", "array"]),
         ("stool", "Stool", "small", ["lathe", "cylinder"]),
         ("bench", "Park Bench", "large", ["box", "cylinder"]),
         ("wardrobe_mirror", "Standing Mirror", "large", ["rounded_box", "mirror"]),
         ("bunk_bed", "Bunk Bed", "large", ["rounded_box", "box"]),
         ("bar_stool", "Bar Stool", "medium", ["lathe", "cylinder"]),
         ("dresser", "Chest of Drawers", "large", ["rounded_box", "box"]),
     ]),
    ("tools", "Hand Tools", "steel + wood grips; silhouette is the whole identity",
     [
         ("hammer", "Claw Hammer", "small", ["box", "extrude_profile"]),
         ("screwdriver", "Screwdriver", "small", ["cylinder", "torus"]),
         ("wrench", "Open-End Wrench", "small", ["extrude_profile", "loft"]),
         ("pliers", "Pliers", "small", ["box", "cylinder", "mirror"]),
         ("hacksaw", "Hacksaw", "small", ["extrude_profile", "thread"]),
         ("file", "Metal File", "small", ["extrude_profile", "subdivide"]),
         ("chisel", "Wood Chisel", "small", ["extrude_profile", "bevel"]),
         ("handsaw", "Handsaw", "large", ["extrude_profile", "bevel"]),
         ("tape_measure", "Tape Measure", "small", ["rounded_box", "cylinder"]),
         ("utility_knife", "Utility Knife", "small", ["box", "bevel"]),
         ("pliers_pipe", "Pipe Wrench", "medium", ["box", "extrude_profile"]),
         ("clamp", "C-Clamp", "medium", ["extrude_profile", "cylinder"]),
         ("mallet", "Wooden Mallet", "medium", ["cylinder", "box"]),
         ("awl", "Awl", "tiny", ["cylinder", "extrude_profile"]),
         ("soldering_iron", "Soldering Iron", "small", ["cylinder", "extrude_profile"]),
         ("level", "Spirit Level", "medium", ["rounded_box", "cylinder"]),
         ("caliper", "Vernier Caliper", "small", ["rounded_box", "extrude_profile"]),
         ("spanner_socket", "Socket Wrench", "small", ["tube", "extrude_profile"]),
     ]),
    ("power_tools", "Power Tools", "plastic shells + metal bits; vents and grips matter",
     [
         ("cordless_drill", "Cordless Drill", "medium", ["rounded_box", "cylinder"]),
         ("circular_saw", "Circular Saw", "medium", ["rounded_box", "extrude_profile"]),
         ("angle_grinder", "Angle Grinder", "medium", ["cylinder", "rounded_box"]),
         ("jigsaw", "Jigsaw", "medium", ["rounded_box", "extrude_profile"]),
         ("heat_gun", "Heat Gun", "medium", ["cylinder", "rounded_box"]),
         ("wood_router", "Wood Router", "medium", ["cylinder", "rounded_box"]),
         ("chainsaw", "Chainsaw", "large", ["rounded_box", "extrude_profile"]),
         ("nail_gun", "Nail Gun", "medium", ["rounded_box", "box"]),
         ("sander", "Orbital Sander", "medium", ["cylinder", "rounded_box"]),
         ("impact_driver", "Impact Driver", "medium", ["cylinder", "rounded_box"]),
         ("welder", "Arc Welder", "large", ["rounded_box", "cylinder"]),
         ("bench_grinder", "Bench Grinder", "large", ["cylinder", "rounded_box"]),
         ("planer", "Hand Planer", "medium", ["rounded_box", "extrude_profile"]),
         ("laser_level", "Laser Level", "small", ["rounded_box", "cylinder"]),
     ]),
    ("hardware", "Hardware & Fasteners", "ISO proportions; threads, hex heads, washers",
     [
         ("hex_bolt", "Hex Bolt M12", "small", ["extrude_profile", "thread"]),
         ("hex_nut", "Hex Nut", "tiny", ["extrude_profile", "thread"]),
         ("washer", "Flat Washer", "micro", ["tube"]),
         ("socket_screw", "Socket Head Screw", "tiny", ["cylinder", "thread"]),
         ("wood_screw", "Wood Screw", "tiny", ["thread", "extrude_profile"]),
         ("spring", "Coil Spring", "small", ["helix", "tube"]),
         ("bearing", "Ball Bearing", "small", ["torus", "sphere", "array"]),
         ("hinge", "Butt Hinge", "small", ["rounded_box", "cylinder"]),
         ("latch", "Toggle Latch", "small", ["box", "cylinder"]),
         ("door_handle", "Door Handle", "small", ["extrude_profile", "cylinder"]),
         ("padlock", "Padlock", "small", ["rounded_box", "torus"]),
         ("chain_link", "Chain Link", "small", ["arc_torus", "array"]),
         ("rope_hook", "Rope Hook", "small", ["arc_torus", "cylinder"]),
         ("clevis_pin", "Clevis Pin", "small", ["cylinder", "torus"]),
         ("grommet", "Rubber Grommet", "tiny", ["tube", "torus"]),
         ("castor_wheel", "Castor Wheel", "small", ["torus", "cylinder", "arc_torus"]),
     ]),
    ("machinery", "Machinery & Mechanical", "gears, bearings, shafts; involute profiles",
     [
         ("spur_gear", "Spur Gear", "small", ["gear", "extrude_profile"]),
         ("helical_gear", "Helical Gear", "small", ["gear", "helix"]),
         ("bevel_gear", "Bevel Gear", "small", ["gear", "extrude_profile"]),
         ("worm_gear", "Worm Gear", "small", ["thread", "gear"]),
         ("chain_sprocket", "Chain Sprocket", "small", ["gear", "array"]),
         ("pulley", "V-Belt Pulley", "small", ["lathe", "extrude_profile"]),
         ("flywheel", "Flywheel", "medium", ["lathe", "spoke"]),
         ("crankshaft", "Crankshaft", "medium", ["cylinder", "box", "array"]),
         ("piston", "Piston", "small", ["lathe", "tube"]),
         ("connecting_rod", "Connecting Rod", "medium", ["extrude_profile", "tube"]),
         ("ball_joint", "Ball Joint", "tiny", ["sphere", "tube"]),
         ("ratchet", "Ratchet Wrench", "small", ["gear", "cylinder"]),
         ("cam_shaft", "Camshaft", "small", ["cylinder", "extrude_profile", "array"]),
         ("clutch_plate", "Clutch Plate", "small", ["lathe", "perforated_panel"]),
         ("spring_plunger", "Spring Plunger", "tiny", ["helix", "cylinder"]),
         ("machine_vise", "Machine Vise", "medium", ["rounded_box", "cylinder"]),
         ("linear_rail", "Linear Rail", "medium", ["extrude_profile", "perforated_panel"]),
         ("stepper_motor", "Stepper Motor", "small", ["cylinder", "rounded_box", "array"]),
     ]),
    ("vehicles_road", "Vehicles - Road", "lofted bodies with real wheelbase and track",
     [
         ("hatchback", "Hatchback Car", "large", ["loft", "torus", "cylinder"]),
         ("sedan", "Saloon Car", "large", ["loft", "torus", "cylinder"]),
         ("sports_car", "Sports Car", "large", ["loft", "torus", "extrude_profile"]),
         ("pickup_truck", "Pickup Truck", "large", ["loft", "torus", "rounded_box"]),
         ("van", "Delivery Van", "large", ["loft", "torus", "cylinder"]),
         ("bus", "City Bus", "huge", ["loft", "torus", "box"]),
         ("truck_tractor", "Semi Tractor", "huge", ["rounded_box", "torus", "cylinder"]),
         ("trailer", "Cargo Trailer", "huge", ["rounded_box", "cylinder", "box"]),
         ("motorcycle", "Motorcycle", "large", ["loft", "torus", "cylinder"]),
         ("scooter", "Scooter", "medium", ["loft", "torus", "extrude_profile"]),
         ("bicycle", "Bicycle", "large", ["torus", "cylinder", "tube"]),
         ("rickshaw", "Rickshaw", "large", ["loft", "torus"]),
         ("go_kart", "Go-Kart", "large", ["rounded_box", "torus", "cylinder"]),
         ("tractor", "Farm Tractor", "huge", ["rounded_box", "torus", "cylinder"]),
         ("bulldozer", "Bulldozer", "huge", ["rounded_box", "tread", "cylinder"]),
         ("forklift", "Forklift", "huge", ["rounded_box", "torus", "box"]),
         ("snowmobile", "Snowmobile", "large", ["loft", "tread", "extrude_profile"]),
         ("wheelbarrow", "Wheelbarrow", "large", ["loft", "torus", "extrude_profile"]),
     ]),
    ("vehicles_rail", "Vehicles - Rail", "long rigid bodies, bogies, couplers",
     [
         ("steam_locomotive", "Steam Locomotive", "huge", ["cylinder", "torus", "rounded_box"]),
         ("diesel_locomotive", "Diesel Locomotive", "huge", ["rounded_box", "tread", "torus"]),
         ("railcar", "Single Railcar", "huge", ["rounded_box", "box"]),
         ("passenger_carriage", "Passenger Coach", "huge", ["loft", "tread", "box"]),
         ("freight_wagon", "Open Freight Wagon", "huge", ["rounded_box", "tread", "box"]),
         ("tank_wagon", "Tank Wagon", "huge", ["cylinder", "tread"]),
         ("hopper_wagon", "Hopper Wagon", "huge", ["extrude_profile", "tread"]),
         ("flatbed_wagon", "Flatbed Wagon", "huge", ["rounded_box", "tread"]),
         ("tram", "Tram", "huge", ["loft", "tread", "torus"]),
         ("subway_train", "Subway Train", "huge", ["rounded_box", "tread"]),
         ("mine_cart", "Mine Cart", "medium", ["extrude_profile", "torus"]),
         ("cable_car", "Cable Car", "huge", ["rounded_box", "cylinder"]),
         ("rail_track", "Rail Track Section", "large", ["extrude_profile", "array"]),
         ("rail_switch", "Rail Switch", "large", ["extrude_profile", "loft"]),
         ("buffer_stop", "Buffer Stop", "large", ["extrude_profile", "box"]),
         ("level_crossing", "Level Crossing Barrier", "large", ["rounded_box", "box"]),
     ]),
    ("vehicles_marine", "Vehicles - Marine", "hull sections, chines, deck fittings",
     [
         ("sailboat", "Sailboat", "large", ["loft", "extrude_profile", "cylinder"]),
         ("motorboat", "Motorboat", "huge", ["loft", "cylinder"]),
         ("yacht", "Motor Yacht", "huge", ["loft", "tube", "cylinder"]),
         ("canoe", "Canoe", "large", ["loft", "extrude_profile"]),
         ("kayak", "Kayak", "large", ["loft", "extrude_profile"]),
         ("rowboat", "Rowboat", "large", ["loft", "extrude_profile"]),
         ("ferry", "Passenger Ferry", "huge", ["loft", "cylinder", "box"]),
         ("cargo_ship", "Container Ship", "huge", ["rounded_box", "box", "cylinder"]),
         ("tugboat", "Tugboat", "huge", ["loft", "cylinder", "torus"]),
         ("fishing_trawler", "Fishing Trawler", "huge", ["loft", "cylinder", "array"]),
         ("submarine", "Submarine", "large", ["lathe", "torus", "extrude_profile"]),
         ("speedboat", "Speedboat", "large", ["loft", "extrude_profile"]),
         ("dinghy", "Dinghy", "small", ["loft", "extrude_profile"]),
         ("jet_ski", "Jet Ski", "medium", ["loft", "extrude_profile"]),
         ("buoy", "Navigation Buoy", "medium", ["lathe", "cylinder"]),
         ("anchor", "Ship Anchor", "small", ["extrude_profile", "arc_torus"]),
     ]),
    ("vehicles_air", "Vehicles - Air", "wings and fuselage are lofted surfaces",
     [
         ("airliner", "Airliner", "huge", ["loft", "extrude_profile", "cylinder"]),
         ("fighter_jet", "Fighter Jet", "huge", ["loft", "extrude_profile"]),
         ("propeller_plane", "Propeller Aircraft", "huge", ["loft", "extrude_profile", "cylinder"]),
         ("glider", "Glider", "huge", ["loft", "extrude_profile"]),
         ("helicopter", "Helicopter", "huge", ["loft", "cylinder", "extrude_profile"]),
         ("quadcopter", "Quadcopter", "medium", ["rounded_box", "cylinder", "array"]),
         ("drone", "Camera Drone", "small", ["rounded_box", "cylinder", "extrude_profile"]),
         ("hot_air_balloon", "Hot Air Balloon", "huge", ["lathe", "tube"]),
         ("airship", "Airship", "huge", ["lathe", "extrude_profile"]),
         ("rocket", "Rocket", "huge", ["lathe", "extrude_profile", "cylinder"]),
         ("turbofan", "Turbofan Engine", "large", ["lathe", "cylinder", "extrude_profile"]),
         ("landing_gear", "Aircraft Landing Gear", "medium", ["cylinder", "torus", "tread"]),
         ("propeller", "Aircraft Propeller", "medium", ["extrude_profile", "array"]),
         ("hangar", "Aircraft Hangar", "huge", ["extrude_profile", "cylinder"]),
     ]),
    ("electronics", "Electronics & Computing", "screens, ports, vents; port layout is computed",
     [
         ("laptop", "Laptop Computer", "medium", ["rounded_box", "box", "extrude_profile"]),
         ("desktop_tower", "Desktop Tower", "medium", ["rounded_box", "perforated_panel"]),
         ("monitor", "Computer Monitor", "large", ["rounded_box", "box"]),
         ("keyboard", "Computer Keyboard", "medium", ["rounded_box", "array"]),
         ("computer_mouse", "Computer Mouse", "small", ["lathe", "subdivide"]),
         ("smartphone", "Smartphone", "small", ["rounded_box", "box"]),
         ("tablet", "Tablet Computer", "medium", ["rounded_box", "box"]),
         ("router", "Wi-Fi Router", "small", ["rounded_box", "cylinder", "array"]),
         ("hard_drive", "Hard Drive", "small", ["rounded_box", "perforated_panel"]),
         ("ssd", "Solid State Drive", "small", ["rounded_box"]),
         ("graphics_card", "Graphics Card", "medium", ["rounded_box", "perforated_panel"]),
         ("server_rack", "Server Rack", "large", ["rounded_box", "perforated_panel", "array"]),
         ("circuit_board", "Circuit Board", "small", ["rounded_box", "box", "array"]),
         ("usb_drive", "USB Flash Drive", "tiny", ["rounded_box", "extrude_profile"]),
         ("webcam", "Webcam", "small", ["cylinder", "rounded_box"]),
         ("headphones", "Headphones", "medium", ["torus", "arc_torus", "rounded_box"]),
         ("speaker", "Loudspeaker", "medium", ["rounded_box", "cylinder", "perforated_panel"]),
         ("smartwatch", "Smartwatch", "small", ["rounded_box", "extrude_profile"]),
     ]),
    ("appliances", "Appliances", "enamelled steel shells, doors, control panels",
     [
         ("refrigerator", "Refrigerator", "huge", ["rounded_box", "box", "cylinder"]),
         ("washing_machine", "Washing Machine", "large", ["rounded_box", "cylinder"]),
         ("dishwasher", "Dishwasher", "large", ["rounded_box", "box"]),
         ("microwave", "Microwave Oven", "medium", ["rounded_box", "box"]),
         ("oven", "Oven", "large", ["rounded_box", "box"]),
         ("stove", "Stove Cooker", "large", ["rounded_box", "torus", "cylinder"]),
         ("toaster", "Toaster", "small", ["rounded_box", "box", "extrude_profile"]),
         ("kettle_electric", "Electric Kettle", "small", ["lathe", "arc_torus"]),
         ("blender", "Blender", "medium", ["lathe", "rounded_box"]),
         ("food_processor", "Food Processor", "medium", ["cylinder", "rounded_box"]),
         ("coffee_machine", "Espresso Machine", "medium", ["rounded_box", "cylinder", "lathe"]),
         ("rice_cooker", "Rice Cooker", "small", ["lathe", "rounded_box"]),
         ("air_fryer", "Air Fryer", "small", ["rounded_box", "cylinder"]),
         ("vacuum_cleaner", "Vacuum Cleaner", "large", ["rounded_box", "cylinder", "tube"]),
         ("fan", "Electric Fan", "medium", ["cylinder", "torus", "rounded_box"]),
         ("heater", "Room Heater", "medium", ["rounded_box", "perforated_panel"]),
         ("humidifier", "Humidifier", "small", ["lathe", "cylinder"]),
         ("iron", "Clothes Iron", "small", ["extrude_profile", "rounded_box"]),
     ]),
    ("lighting", "Lighting & Electrical", "shades, sockets, diffusers",
     [
         ("desk_lamp", "Desk Lamp", "small", ["lathe", "cylinder", "box"]),
         ("floor_lamp", "Floor Lamp", "large", ["lathe", "cylinder", "arc_torus"]),
         ("pendant_lamp", "Pendant Lamp", "small", ["lathe", "cylinder"]),
         ("chandelier", "Chandelier", "medium", ["lathe", "array", "torus"]),
         ("ceiling_fixture", "Ceiling Light", "small", ["lathe", "cylinder"]),
         ("street_lamp", "Street Lamp", "large", ["cylinder", "lathe", "extrude_profile"]),
         ("light_switch", "Light Switch", "small", ["rounded_box", "box"]),
         ("power_socket", "Power Socket", "small", ["rounded_box", "box"]),
         ("extension_lead", "Extension Lead", "small", ["rounded_box", "tube"]),
         ("battery", "AA Battery", "tiny", ["cylinder", "lathe"]),
         ("power_bank", "Power Bank", "small", ["rounded_box", "extrude_profile"]),
         ("light_bulb", "LED Bulb", "small", ["lathe", "cylinder"]),
         ("torch", "Flashlight", "small", ["cylinder", "lathe"]),
         ("solar_panel", "Solar Panel", "large", ["rounded_box", "perforated_panel"]),
         ("wind_turbine", "Wind Turbine", "huge", ["cylinder", "extrude_profile"]),
     ]),
    ("plumbing", "Plumbing & Bathroom", "ceramic and chrome; always symmetric",
     [
         ("toilet", "Toilet", "large", ["lathe", "rounded_box"]),
         ("washbasin", "Washbasin", "medium", ["lathe", "rounded_box"]),
         ("bathtub", "Bathtub", "large", ["loft", "rounded_box"]),
         ("shower_head", "Shower Head", "small", ["cylinder", "lathe", "perforated_panel"]),
         ("tap", "Basin Tap", "small", ["lathe", "cylinder", "arc_torus"]),
         ("sink", "Kitchen Sink", "medium", ["rounded_box", "extrude_profile"]),
         ("urinal", "Urinal", "small", ["lathe", "extrude_profile"]),
         ("bathroom_scale", "Bathroom Scale", "small", ["rounded_box", "extrude_profile"]),
         ("toothbrush", "Toothbrush", "tiny", ["rounded_box", "array"]),
         ("soap_dispenser", "Soap Dispenser", "small", ["cylinder", "lathe"]),
         ("plunger", "Plunger", "small", ["lathe", "cylinder"]),
         ("pipe", "Pipe Section", "medium", ["tube", "cylinder"]),
         ("valve", "Ball Valve", "small", ["cylinder", "lever", "torus"]),
         ("water_tap", "Outdoor Tap", "small", ["cylinder", "lathe"]),
         ("bidet", "Bidet", "medium", ["lathe", "rounded_box"]),
     ]),
    ("medical", "Medical & Laboratory", "instruments with fine tolerances",
     [
         ("syringe", "Syringe", "small", ["cylinder", "lathe", "extrude_profile"]),
         ("iv_drip", "IV Drip Stand", "large", ["cylinder", "tube", "array"]),
         ("stethoscope", "Stethoscope", "small", ["tube", "arc_torus", "sphere"]),
         ("thermometer", "Clinical Thermometer", "small", ["cylinder", "lathe"]),
         ("microscope", "Optical Microscope", "medium", ["cylinder", "box", "lens"]),
         ("centrifuge", "Centrifuge", "medium", ["rounded_box", "cylinder"]),
         ("petri_dish", "Petri Dish", "tiny", ["cylinder", "tube"]),
         ("test_tube", "Test Tube", "small", ["cylinder", "lathe"]),
         ("erlenmeyer_flask", "Conical Flask", "small", ["lathe"]),
         ("beaker", "Beaker", "small", ["lathe", "extrude_profile"]),
         ("graduated_cylinder", "Graduated Cylinder", "medium", ["lathe", "extrude_profile"]),
         ("pipette", "Pipette", "small", ["lathe", "cylinder"]),
         ("defibrillator", "Defibrillator", "medium", ["rounded_box", "box", "cylinder"]),
         ("wheelchair", "Wheelchair", "large", ["torus", "rounded_box", "cylinder"]),
         ("crutches", "Crutches", "large", ["cylinder", "tube", "extrude_profile"]),
         ("hospital_bed", "Hospital Bed", "large", ["rounded_box", "cylinder", "box"]),
         ("forceps", "Forceps", "small", ["extrude_profile", "array"]),
         ("scalpel", "Scalpel", "small", ["extrude_profile", "bevel"]),
     ]),
    ("optics", "Optical & Photographic", "lens barrels and blades; symmetry is obvious",
     [
         ("camera_lens", "Camera Lens", "medium", ["lathe", "tube", "extrude_profile"]),
         ("dslr_camera", "DSLR Camera", "small", ["rounded_box", "cylinder", "lathe"]),
         ("camera_body", "Mirrorless Camera", "small", ["rounded_box", "box"]),
         ("tripod", "Tripod", "large", ["cylinder", "array", "extrude_profile"]),
         ("binoculars", "Binoculars", "small", ["cylinder", "rounded_box"]),
         ("telescope", "Telescope", "large", ["cylinder", "lathe", "tread"]),
         ("microscope_eyepiece", "Eyepiece", "tiny", ["lathe", "tube"]),
         ("projector", "Projector", "medium", ["rounded_box", "cylinder", "perforated_panel"]),
         ("film_reel", "Film Reel", "small", ["cylinder", "torus", "perforated_panel"]),
         ("camera_flash", "Speedlight", "small", ["rounded_box", "box"]),
         ("light_meter", "Light Meter", "small", ["rounded_box", "extrude_profile"]),
         ("drone_camera", "Drone Gimbal Camera", "small", ["sphere", "cylinder", "rounded_box"]),
     ]),
    ("science", "Scientific Instruments", "dials, scales, precise housings",
     [
         ("oscilloscope", "Oscilloscope", "medium", ["rounded_box", "box", "perforated_panel"]),
         ("function_generator", "Function Generator", "medium", ["rounded_box", "box"]),
         ("multimeter", "Digital Multimeter", "small", ["rounded_box", "extrude_profile"]),
         ("power_supply", "Lab Power Supply", "medium", ["rounded_box", "perforated_panel"]),
         ("balance", "Analytical Balance", "small", ["cylinder", "lathe", "extrude_profile"]),
         ("fume_hood", "Fume Hood", "large", ["rounded_box", "box"]),
         ("autoclave", "Autoclave", "medium", ["cylinder", "rounded_box"]),
         ("spectrometer", "Spectrometer", "medium", ["box", "cylinder", "extrude_profile"]),
         ("laser", "Laser Unit", "small", ["rounded_box", "cylinder"]),
         ("clamp_stand", "Laboratory Clamp Stand", "large", ["cylinder", "box"]),
         ("bunsen_burner", "Bunsen Burner", "small", ["cylinder", "lathe"]),
         ("magnet", "Bar Magnet", "tiny", ["rounded_box", "extrude_profile"]),
         ("inductor_coil", "Induction Coil", "small", ["helix", "tube"]),
         ("capacitor", "Capacitor", "tiny", ["cylinder", "lathe"]),
     ]),
    ("music", "Musical Instruments", "symmetry and string layout; rosewood/brass",
     [
         ("acoustic_guitar", "Acoustic Guitar", "large", ["lathe", "extrude_profile", "tube"]),
         ("electric_guitar", "Electric Guitar", "large", ["extrude_profile", "rounded_box"]),
         ("violin", "Violin", "medium", ["lathe", "extrude_profile", "box"]),
         ("cello", "Cello", "large", ["lathe", "extrude_profile"]),
         ("upright_piano", "Upright Piano", "huge", ["rounded_box", "box", "array"]),
         ("grand_piano", "Grand Piano", "huge", ["loft", "rounded_box", "box"]),
         ("synthesizer", "Synthesizer", "medium", ["rounded_box", "box", "array"]),
         ("drum_kit", "Drum Kit", "large", ["cylinder", "lathe", "array"]),
         ("violin_bow", "Violin Bow", "large", ["extrude_profile", "cylinder"]),
         ("flute", "Flute", "medium", ["cylinder", "lathe"]),
         ("clarinet", "Clarinet", "medium", ["lathe", "cylinder", "array"]),
         ("trumpet", "Trumpet", "large", ["tube", "lathe"]),
         ("trombone", "Trombone", "large", ["tube", "lathe"]),
         ("saxophone", "Saxophone", "medium", ["lathe", "tube", "arc_torus"]),
         ("accordion", "Accordion", "medium", ["rounded_box", "perforated_panel"]),
         ("harmonica", "Harmonica", "medium", ["rounded_box", "perforated_panel"]),
         ("tuning_fork", "Tuning Fork", "medium", ["extrude_profile", "cylinder"]),
         ("metronome", "Metronome", "small", ["extrude_profile", "box"]),
     ]),
    ("sports", "Sports & Fitness", "equipment; tubes, grips, and markings",
     [
         ("football", "Football", "small", ["lathe", "perforated_panel", "subdivide"]),
         ("basketball", "Basketball", "small", ["sphere", "perforated_panel"]),
         ("tennis_racket", "Tennis Racket", "large", ["torus", "extrude_profile", "array"]),
         ("golf_club", "Golf Club", "large", ["extrude_profile", "lathe"]),
         ("bicycle_helmet", "Bicycle Helmet", "small", ["lathe", "subdivide", "extrude_profile"]),
         ("ski", "Ski", "large", ["extrude_profile", "bevel"]),
         ("snowboard", "Snowboard", "large", ["extrude_profile", "subdivide"]),
         ("dumbbell", "Dumbbell", "small", ["cylinder", "tube", "barbell"]),
         ("kettlebell", "Kettlebell", "small", ["torus", "sphere"]),
         ("baseball_bat", "Baseball Bat", "large", ["lathe", "subdivide"]),
         ("hockey_stick", "Hockey Stick", "large", ["extrude_profile", "bevel"]),
         ("surfboard", "Surfboard", "large", ["loft", "extrude_profile"]),
         ("skateboard", "Skateboard", "medium", ["rounded_box", "extrude_profile", "tread"]),
         ("climbing_hold", "Climbing Hold", "small", ["subdivide", "sphere"]),
         ("yoga_mat", "Yoga Mat", "large", ["rounded_box", "cylinder"]),
         ("boxing_punching_bag", "Punching Bag", "large", ["lathe", "cylinder"]),
         ("stopwatch", "Stopwatch", "small", ["cylinder", "extrude_profile"]),
         ("whistle", "Referee Whistle", "tiny", ["lathe", "extrude_profile"]),
     ]),
    ("toys", "Toys & Games", "bold colours, chunky proportions, correct count",
     [
         ("teddy_bear", "Teddy Bear", "small", ["sphere", "subdivide", "lathe"]),
         ("lego_brick", "Lego Brick", "tiny", ["rounded_box", "cylinder", "array"]),
         ("rubik_cube", "Rubik's Cube", "tiny", ["rounded_box", "array"]),
         ("toy_car", "Toy Car", "small", ["rounded_box", "torus", "cylinder"]),
         ("toy_train", "Toy Train", "small", ["rounded_box", "cylinder", "array"]),
         ("doll", "Doll", "small", ["lathe", "sphere", "subdivide"]),
         ("teddy_blocks", "Building Blocks", "tiny", ["rounded_box", "array"]),
         ("yo_yo", "Yo-Yo", "tiny", ["lathe", "tube", "cylinder"]),
         ("spinning_top", "Spinning Top", "small", ["lathe", "cylinder"]),
         ("kite", "Kite", "large", ["extrude_profile", "tube"]),
         ("frisbee", "Frisbee", "small", ["lathe", "tube"]),
         ("chess_set", "Chess Set", "small", ["lathe", "array"]),
         ("dice", "Dice", "tiny", ["rounded_box", "perforated_panel"]),
         ("domino", "Domino", "tiny", ["rounded_box", "perforated_panel"]),
         ("jigsaw_puzzle", "Jigsaw Puzzle Piece", "tiny", ["extrude_profile", "bevel"]),
         ("marble", "Marble", "tiny", ["sphere"]),
         ("jack_in_box", "Jack-in-the-Box", "small", ["rounded_box", "subdivide"]),
         ("water_gun", "Water Gun", "medium", ["rounded_box", "cylinder"]),
     ]),
    ("office", "Stationery & Office", "small precision objects; layout is computed",
     [
         ("pen", "Ballpoint Pen", "small", ["cylinder", "lathe", "extrude_profile"]),
         ("pencil", "Pencil", "small", ["hex_prism", "lathe", "extrude_profile"]),
         ("notebook", "Notebook", "small", ["rounded_box", "box"]),
         ("stapler", "Stapler", "small", ["rounded_box", "extrude_profile"]),
         ("hole_punch", "Hole Punch", "small", ["rounded_box", "cylinder"]),
         ("paperclip", "Paperclip", "tiny", ["helix", "tube"]),
         ("scissors", "Scissors", "small", ["extrude_profile", "cylinder", "torus"]),
         ("envelope", "Envelope", "small", ["rounded_box", "bevel"]),
         ("paper_stack", "Paper Stack", "small", ["rounded_box", "array"]),
         ("desk_organiser", "Desk Organiser", "small", ["rounded_box", "box", "perforated_panel"]),
         ("whiteboard", "Whiteboard", "large", ["rounded_box", "box"]),
         ("binder_clip", "Binder Clip", "tiny", ["extrude_profile", "arc_torus"]),
         ("rubber_stamp", "Rubber Stamp", "tiny", ["cylinder", "rounded_box"]),
         ("label_maker", "Label Maker", "small", ["rounded_box", "extrude_profile"]),
         ("calculator", "Calculator", "small", ["rounded_box", "box", "array"]),
         ("clipboard", "Clipboard", "medium", ["rounded_box", "box", "clip"]),
         ("tape_dispenser", "Tape Dispenser", "small", ["lathe", "extrude_profile"]),
         ("push_pin", "Push Pin", "tiny", ["cylinder", "cone", "sphere"]),
     ]),
    ("containers", "Containers & Packaging", "labels and closures read as real packaging",
     [
         ("cardboard_box", "Cardboard Box", "medium", ["rounded_box", "box", "flap"]),
         ("bottle", "PET Bottle", "small", ["lathe", "thread"]),
         ("glass_jar", "Glass Jar", "small", ["lathe", "thread"]),
         ("can", "Drinks Can", "small", ["lathe", "tube"]),
         ("carton", "Milk Carton", "small", ["extrude_profile", "box"]),
         ("tote_bag", "Tote Bag", "small", ["loft", "arc_torus", "subdivide"]),
         ("suitcase", "Suitcase", "medium", ["rounded_box", "cylinder", "box"]),
         ("bucket", "Bucket", "small", ["lathe", "arc_torus"]),
         ("crate", "Wooden Crate", "medium", ["box", "array"]),
         ("barrel", "Oil Barrel", "medium", ["lathe", "torus"]),
         ("drum", "Steel Drum", "medium", ["lathe", "torus"]),
         ("thermos", "Thermos Flask", "small", ["lathe", "cylinder"]),
         ("tiffin_box", "Lunch Box", "small", ["rounded_box", "clip"]),
         ("shopping_bag", "Paper Shopping Bag", "small", ["loft", "box"]),
         ("wine_bottle", "Wine Bottle", "small", ["lathe", "thread"]),
         ("paint_can", "Paint Can", "small", ["lathe", "cylinder"]),
         ("first_aid_kit", "First Aid Kit", "small", ["rounded_box", "cross"]),
         ("cage_crate", "Pet Carrier", "medium", ["rounded_box", "perforated_panel"]),
     ]),
    ("agriculture", "Agriculture & Farming", "working tools and machinery",
     [
         ("plough", "Mouldboard Plough", "huge", ["extrude_profile", "cylinder", "array"]),
         ("harrow", "Disc Harrow", "huge", ["torus", "array", "extrude_profile"]),
         ("seed_drill", "Seed Drill", "huge", ["rounded_box", "cylinder", "array"]),
         ("combine_harvester", "Combine Harvester", "huge", ["rounded_box", "cylinder", "tread"]),
         ("water_pump", "Water Pump", "medium", ["cylinder", "rounded_box", "pipe"]),
         ("silo", "Grain Silo", "huge", ["cylinder", "cone", "rounded_box"]),
         ("greenhouse", "Greenhouse", "large", ["rounded_box", "glass", "tube"]),
         ("watering_can", "Watering Can", "medium", ["lathe", "tube", "arc_torus"]),
         ("garden_hose", "Garden Hose", "large", ["helix", "tube"]),
         ("watering_pivot", "Pivot Irrigation Sprinkler", "medium", ["tube", "array", "cylinder"]),
         ("wheelbarrow_buckets", "Grain Bucket", "small", ["lathe", "arc_torus"]),
         ("egg_incubator", "Egg Incubator", "medium", ["rounded_box", "cylinder"]),
         ("beehive", "Beehive", "medium", ["box", "array", "loft"]),
         ("chicken_coop", "Chicken Coop", "large", ["rounded_box", "perforated_panel"]),
         ("fence_post", "Fence Post", "medium", ["box", "bevel"]),
         ("scarecrow", "Scarecrow", "large", ["box", "cylinder", "loft"]),
         ("tarp", "Tarp", "large", ["subdivide", "rounded_box"]),
         ("rain_barrel", "Rain Barrel", "medium", ["lathe", "tube"]),
     ]),
    ("construction", "Construction & Building", "structural members with exact sections",
     [
         ("i_beam", "I-Beam", "large", ["extrude_profile", "box"]),
         ("channel_beam", "Channel Beam", "large", ["extrude_profile"]),
         ("steel_column", "Steel Column", "large", ["extrude_profile", "box"]),
         ("rebar", "Reinforcing Bar", "large", ["cylinder", "thread"]),
         ("brick", "Brick", "small", ["rounded_box", "bevel"]),
         ("concrete_block", "Concrete Block", "medium", ["rounded_box", "perforated_panel"]),
         ("roof_tile", "Roof Tile", "small", ["extrude_profile", "subdivide"]),
         ("truss", "Roof Truss", "large", ["extrude_profile", "array"]),
         ("scaffold_frame", "Scaffold Frame", "huge", ["cylinder", "array"]),
         ("wheelbarrow_tray", "Mortar Trowel", "medium", ["extrude_profile", "bevel"]),
         ("cement_mixer", "Cement Mixer", "large", ["cylinder", "rounded_box", "torus"]),
         ("jackhammer", "Jackhammer", "medium", ["rounded_box", "extrude_profile"]),
         ("spirit_level_long", "Long Spirit Level", "large", ["rounded_box", "cylinder"]),
         ("scaffold_plank", "Scaffold Plank", "large", ["rounded_box", "bevel"]),
         ("crane_hook", "Crane Hook", "large", ["arc_torus", "extrude_profile"]),
         ("wall_tile", "Wall Tile", "small", ["rounded_box", "bevel"]),
         ("gutter", "Rain Gutter", "large", ["extrude_profile", "tube"]),
         ("downpipe", "Downpipe", "large", ["tube", "cylinder"]),
     ]),
    ("architecture", "Architecture & Structures", "massing, openings, roofs",
     [
         ("greek_column", "Greek Column", "huge", ["lathe", "flute", "extrude_profile"]),
         ("stone_arch", "Stone Arch", "large", ["extrude_profile", "arc_torus"]),
         ("dome", "Geodesic Dome", "huge", ["sphere", "array", "tube"]),
         ("gothic_window", "Gothic Window", "medium", ["extrude_profile", "arc_torus"]),
         ("pagoda", "Pagoda", "huge", ["loft", "extrude_profile", "array"]),
         ("lighthouse", "Lighthouse", "huge", ["lathe", "cylinder", "lathe"]),
         ("windmill", "Windmill", "huge", ["cylinder", "extrude_profile", "lathe"]),
         ("water_tower", "Water Tower", "huge", ["cylinder", "cone", "lathe"]),
         ("gazebo", "Gazebo", "large", ["extrude_profile", "cylinder", "array"]),
         ("pergola", "Pergola", "large", ["box", "array", "extrude_profile"]),
         ("obelisk", "Obelisk", "huge", ["extrude_profile", "cone"]),
         ("temple", "Classical Temple", "huge", ["box", "extrude_profile", "lathe"]),
         ("stone_arch_bridge", "Stone Bridge", "huge", ["extrude_profile", "arc_torus"]),
         ("viaduct", "Viaduct", "huge", ["extrude_profile", "arc_torus", "array"]),
         ("clock_tower", "Clock Tower", "huge", ["rounded_box", "lathe", "extrude_profile"]),
         ("stained_glass", "Stained Glass Panel", "large", ["extrude_profile", "bevel"]),
         ("staircase", "Staircase", "large", ["box", "array", "extrude_profile"]),
         ("balcony", "Balcony", "large", ["rounded_box", "array", "cylinder"]),
     ]),
    ("urban", "Urban & Street Furniture", "public infrastructure; spacing is computed",
     [
         ("bench_public", "Public Bench", "large", ["box", "cylinder", "slat"]),
         ("bus_shelter", "Bus Shelter", "large", ["rounded_box", "glass", "box"]),
         ("bollard", "Bollard", "large", ["lathe", "cylinder"]),
         ("traffic_cone", "Traffic Cone", "medium", ["lathe", "cone", "torus"]),
         ("parking_meter", "Parking Meter", "large", ["rounded_box", "cylinder"]),
         ("street_sign", "Street Sign", "large", ["extrude_profile", "cylinder"]),
         ("mailbox", "Mailbox", "large", ["rounded_box", "cylinder", "lathe"]),
         ("fire_hydrant", "Fire Hydrant", "large", ["lathe", "cylinder", "torus"]),
         ("manhole_cover", "Manhole Cover", "large", ["cylinder", "perforated_panel"]),
         ("drain_grate", "Drain Grate", "medium", ["box", "perforated_panel"]),
         ("bike_rack", "Bike Rack", "large", ["arc_torus", "array", "cylinder"]),
         ("phone_booth", "Phone Booth", "large", ["rounded_box", "glass", "box"]),
         ("trash_bin", "Public Bin", "medium", ["lathe", "cylinder", "box"]),
         ("kiosk", "News Kiosk", "large", ["rounded_box", "box", "cylinder"]),
         ("pedestrian_crossing", "Zebra Crossing Post", "large", ["cylinder", "extrude_profile"]),
         ("statue", "Monument Statue", "large", ["lathe", "subdivide", "extrude_profile"]),
         ("fountain", "Fountain", "large", ["lathe", "cylinder", "sphere"]),
         ("planter_box", "Street Planter", "medium", ["rounded_box", "loft"]),
     ]),
    ("clothing", "Clothing & Textiles", "draped forms; thickness is what sells it",
     [
         ("t_shirt", "T-Shirt", "medium", ["loft", "subdivide", "solidify"]),
         ("hoodie", "Hoodie", "medium", ["loft", "subdivide", "arc_torus"]),
         ("jeans", "Jeans", "medium", ["loft", "subdivide"]),
         ("dress", "Dress", "medium", ["lathe", "subdivide", "loft"]),
         ("suit_jacket", "Suit Jacket", "medium", ["loft", "subdivide", "solidify"]),
         ("trench_coat", "Trench Coat", "large", ["loft", "subdivide"]),
         ("winter_boot", "Winter Boot", "medium", ["extrude_profile", "loft"]),
         ("sneaker", "Sneaker", "medium", ["loft", "extrude_profile", "lacing"]),
         ("sun_hat", "Sun Hat", "medium", ["lathe", "extrude_profile"]),
         ("scarf", "Scarf", "medium", ["loft", "subdivide"]),
         ("glove", "Glove", "small", ["loft", "subdivide", "fingers"]),
         ("backpack", "Backpack", "medium", ["rounded_box", "tube", "zipper"]),
         ("suitcase_cloth", "Holdall", "medium", ["loft", "rounded_box", "arc_torus"]),
         ("apron", "Apron", "medium", ["extrude_profile", "subdivide"]),
         ("umbrella", "Umbrella", "large", ["lathe", "array", "cylinder"]),
         ("ski_goggles", "Ski Goggles", "medium", ["torus", "rounded_box"]),
         ("swimsuit", "Swimsuit", "medium", ["loft", "subdivide"]),
         ("towel", "Bath Towel", "medium", ["subdivide", "loft", "solidify"]),
     ]),
    ("jewellery", "Jewelry & Accessories", "thin metal; every radius is deliberate",
     [
         ("ring", "Wedding Ring", "tiny", ["torus", "lathe"]),
         ("necklace", "Pendant Necklace", "tiny", ["helix", "torus", "sphere"]),
         ("earring", "Earring", "micro", ["torus", "sphere", "arc_torus"]),
         ("bracelet", "Bracelet", "small", ["torus", "helix", "array"]),
         ("watch", "Wristwatch", "small", ["torus", "cylinder", "rounded_box"]),
         ("sunglasses", "Sunglasses", "small", ["torus", "rounded_box", "lens"]),
         ("wallet", "Wallet", "small", ["rounded_box", "stitch", "box"]),
         ("belt", "Belt", "medium", ["extrude_profile", "rounded_box", "buckle"]),
         ("hat", "Hat", "medium", ["lathe", "extrude_profile"]),
         ("brooch", "Brooch", "micro", ["sphere", "torus", "array"]),
         ("cufflink", "Cufflink", "tiny", ["cylinder", "torus", "rounded_box"]),
         ("pendant", "Pendant", "tiny", ["lathe", "sphere", "torus"]),
         ("hairpin", "Hairpin", "tiny", ["arc_torus", "tube"]),
         ("keychain", "Keychain", "tiny", ["torus", "extrude_profile", "ring"]),
         ("scarf_ring", "Scarf Ring", "tiny", ["torus", "tube"]),
         ("signet_ring", "Signet Ring", "tiny", ["torus", "lathe", "extrude_profile"]),
         ("anklet", "Anklet", "small", ["helix", "torus"]),
         ("tie_clip", "Tie Clip", "tiny", ["rounded_box", "extrude_profile"]),
     ]),
    ("timepieces", "Timepieces & Instruments", "dial layout is the identity",
     [
         ("grandfather_clock", "Grandfather Clock", "large", ["rounded_box", "lathe", "pendulum"]),
         ("wall_clock", "Wall Clock", "small", ["cylinder", "lathe", "extrude_profile"]),
         ("alarm_clock", "Alarm Clock", "small", ["cylinder", "rounded_box", "bell"]),
         ("pocket_watch", "Pocket Watch", "tiny", ["cylinder", "lathe", "torus"]),
         ("sundial", "Sundial", "medium", ["lathe", "extrude_profile"]),
         ("hourglass", "Hourglass", "small", ["lathe", "sphere", "tube"]),
         ("metronome_clock", "Metronome", "small", ["extrude_profile", "box", "pendulum"]),
         ("calendar_clock", "Desk Calendar", "small", ["rounded_box", "box", "rings"]),
         ("timer", "Kitchen Timer", "small", ["cylinder", "rounded_box", "lathe"]),
         ("atomic_clock", "Radio-Controlled Clock", "tiny", ["rounded_box", "lathe"]),
         ("stopwatch_large", "Split Timer", "small", ["cylinder", "extrude_profile", "strap"]),
         ("astrolabe", "Astrolabe", "small", ["torus", "extrude_profile", "array"]),
     ]),
    ("botany", "Plants & Botany", "branching systems; phyllotaxis matters",
     [
         ("tree_oak", "Oak Tree", "huge", ["branch", "subdivide", "cluster"]),
         ("pine_tree", "Pine Tree", "huge", ["cone", "branch", "cluster"]),
         ("palm_tree", "Palm Tree", "huge", ["cylinder", "frond", "cluster"]),
         ("shrub", "Shrub", "medium", ["cluster", "subdivide", "sphere"]),
         ("rose", "Rose", "small", ["subdivide", "petal", "stem"]),
         ("tulip", "Tulip", "small", ["lathe", "petal", "stem"]),
         ("succulent", "Succulent", "tiny", ["lathe", "subdivide", "array"]),
         ("cactus", "Cactus", "small", ["lathe", "cylinder", "fibre"]),
         ("fern", "Fern", "medium", ["frond", "stem", "subdivide"]),
         ("mushroom", "Mushroom", "small", ["lathe", "subdivide", "stem"]),
         ("bonsai", "Bonsai Tree", "medium", ["branch", "pot", "subdivide"]),
         ("flower_pot", "Flower Pot", "small", ["lathe", "torus"]),
         ("vine", "Climbing Vine", "large", ["helix", "leaf", "stem"]),
         ("grass_tuft", "Grass Tuft", "tiny", ["blade", "array"]),
         ("wheat", "Wheat Stalk", "small", ["stem", "grain", "array"]),
         ("sunflower", "Sunflower", "small", ["petal", "lathe", "stem"]),
         ("orchid", "Orchid", "small", ["petal", "lathe", "stem"]),
         ("bonsai_pot", "Cascade Pot", "small", ["lathe", "extrude_profile"]),
     ]),
    ("animals_mammal", "Animals - Mammals", "quadruped armature; proportion over detail",
     [
         ("dog", "Dog", "medium", ["quadruped", "subdivide", "tail"]),
         ("cat", "Cat", "large", ["quadruped", "subdivide", "tail"]),
         ("horse", "Horse", "large", ["quadruped", "neck", "tail"]),
         ("cow", "Cow", "large", ["quadruped", "udder", "tail"]),
         ("sheep", "Sheep", "medium", ["quadruped", "wool", "tail"]),
         ("pig", "Pig", "medium", ["quadruped", "subdivide", "tail"]),
         ("elephant", "Elephant", "huge", ["quadruped", "trunk", "ears"]),
         ("giraffe", "Giraffe", "huge", ["quadruped", "neck", "horns"]),
         ("lion", "Lion", "large", ["quadruped", "mane", "tail"]),
         ("tiger", "Tiger", "large", ["quadruped", "tail", "stripes"]),
         ("bear", "Bear", "large", ["quadruped", "subdivide", "tail"]),
         ("rabbit", "Rabbit", "medium", ["quadruped", "ears", "tail"]),
         ("squirrel", "Squirrel", "medium", ["quadruped", "bushy_tail", "ears"]),
         ("fox", "Fox", "medium", ["quadruped", "bushy_tail", "ears"]),
         ("monkey", "Monkey", "small", ["quadruped", "tail", "arms"]),
         ("hippo", "Hippopotamus", "huge", ["quadruped", "subdivide"]),
         ("deer", "Deer", "large", ["quadruped", "antlers", "tail"]),
         ("camel", "Camel", "huge", ["quadruped", "hump", "neck"]),
     ]),
    ("animals_bird", "Animals - Birds", "wings, beak, tail; silhouette is everything",
     [
         ("eagle", "Eagle", "large", ["bird", "wings", "tail"]),
         ("sparrow", "Sparrow", "tiny", ["bird", "wings", "tail"]),
         ("owl", "Owl", "medium", ["bird", "eyes", "wings"]),
         ("duck", "Duck", "medium", ["bird", "beak", "webbed_feet"]),
         ("penguin", "Penguin", "medium", ["bird", "wings", "webbed_feet"]),
                         ("seagull", "Seagull", "medium", ["bird", "wings", "beak"]),
                         ("flamingo", "Flamingo", "large", ["bird", "legs", "neck"]),
                         ("parrot", "Parrot", "small", ["bird", "beak", "tail"]),
                         ("peacock", "Peacock", "large", ["bird", "tail_feathers", "crest"]),
                         ("woodpecker", "Woodpecker", "small", ["bird", "beak", "tail"]),
                         ("swan", "Swan", "large", ["bird", "neck", "webbed_feet"]),
                         ("chicken", "Chicken", "tiny", ["bird", "comb", "beak"]),
                         ("rooster", "Rooster", "small", ["bird", "comb", "tail"]),
                         ("hummingbird", "Hummingbird", "tiny", ["bird", "wings", "beak"]),
                         ("stork", "Stork", "large", ["bird", "legs", "beak"]),
                         ("crow", "Crow", "small", ["bird", "beak", "tail"]),
                         ("ostrich", "Ostrich", "large", ["bird", "legs", "neck"]),
                         ("pelican", "Pelican", "large", ["bird", "pouch", "webbed_feet"]),
     ]),
    ("animals_aquatic", "Animals - Aquatic", "streamlined bodies; fins are thin surfaces",
     [
         ("goldfish", "Goldfish", "tiny", ["fish", "fins", "tail"]),
         ("shark", "Shark", "large", ["fish", "fins", "dorsal"]),
         ("tuna", "Tuna", "large", ["fish", "fins", "tail"]),
         ("salmon", "Salmon", "medium", ["fish", "fins", "tail"]),
         ("clownfish", "Clownfish", "tiny", ["fish", "fins", "stripes"]),
         ("octopus", "Octopus", "medium", ["arms", "head", "suckers"]),
         ("squid", "Squid", "medium", ["cone", "tentacles", "fins"]),
         ("crab", "Crab", "small", ["legs", "shell", "claws"]),
         ("lobster", "Lobster", "medium", ["legs", "shell", "claws"]),
         ("jellyfish", "Jellyfish", "medium", ["bell", "tentacles", "translucent"]),
         ("starfish", "Starfish", "small", ["star", "arms", "subdivide"]),
         ("seahorse", "Seahorse", "tiny", ["curved_body", "fin", "snout"]),
         ("whale", "Whale", "huge", ["fish", "fins", "tail"]),
         ("dolphin", "Dolphin", "large", ["fish", "beak", "dorsal"]),
         ("turtle", "Sea Turtle", "large", ["shell", "flippers", "head"]),
         ("coral", "Coral", "small", ["branch", "subdivide", "cluster"]),
         ("sea_urchin", "Sea Urchin", "tiny", ["spikes", "sphere", "array"]),
         ("hermit_crab", "Hermit Crab", "tiny", ["spiral", "legs", "claws"]),
     ]),
    ("animals_other", "Animals - Reptiles, Insects & Small", "segmented and many-legged",
     [
         ("snake", "Snake", "medium", ["helix", "scales", "taper"]),
         ("lizard", "Lizard", "tiny", ["quadruped", "scales", "tail"]),
         ("turtle_land", "Tortoise", "small", ["shell", "legs", "head"]),
         ("crocodile", "Crocodile", "large", ["elongated", "legs", "scutes"]),
         ("frog", "Frog", "tiny", ["body", "legs", "webbed_feet"]),
         ("salamander", "Salamander", "tiny", ["elongated", "legs", "tail"]),
         ("spider", "Spider", "small", ["legs", "body", "cephalothorax"]),
         ("ant", "Ant", "micro", ["segments", "legs", "antennae"]),
         ("bee", "Honeybee", "micro", ["segments", "wings", "stripes"]),
         ("beetle", "Beetle", "small", ["shell", "legs", "antennae"]),
         ("butterfly", "Butterfly", "small", ["wings", "body", "pattern"]),
         ("dragonfly", "Dragonfly", "small", ["wings", "body", "eyes"]),
         ("grasshopper", "Grasshopper", "small", ["legs", "wings", "body"]),
         ("centipede", "Centipede", "small", ["segments", "legs", "array"]),
         ("snail", "Snail", "tiny", ["spiral", "shell", "body"]),
         ("slug", "Slug", "tiny", ["body", "tentacles", "foot"]),
                         ("mantis", "Praying Mantis", "small", ["body", "legs", "wings"]),
                         ("tadpole", "Tadpole", "micro", ["tail", "body", "head"]),
     ]),
    ("human", "Human Body & Anatomy", "proportion canon: 7.5 heads tall",
     [
         ("human_skull", "Human Skull", "small", ["sculpt", "sphere", "subdivide"]),
         ("human_hand", "Human Hand", "small", ["bones", "fingers", "subdivide"]),
         ("human_foot", "Human Foot", "small", ["bones", "subdivide"]),
         ("human_arm", "Human Arm", "medium", ["bones", "muscle", "subdivide"]),
         ("human_leg", "Human Leg", "medium", ["bones", "muscle", "subdivide"]),
         ("human_torso", "Human Torso", "medium", ["sculpt", "subdivide", "lathe"]),
         ("human_head", "Human Head", "small", ["sculpt", "sphere", "subdivide"]),
         ("human_ear", "Human Ear", "tiny", ["lathe", "subdivide"]),
         ("human_nose", "Human Nose", "tiny", ["sculpt", "lathe"]),
         ("human_eye", "Human Eye", "tiny", ["sphere", "lathe", "iris"]),
         ("human_hand_skeleton", "Hand Bones", "small", ["bones", "array"]),
         ("human_spine", "Human Spine", "medium", ["vertebrae", "array", "curve"]),
         ("human_ribcage", "Rib Cage", "medium", ["ribs", "array", "curve"]),
         ("human_pelvis", "Human Pelvis", "medium", ["bones", "lathe", "subdivide"]),
         ("human_brain", "Human Brain", "small", ["subdivide", "lobes"]),
                         ("human_heart", "Human Heart", "small", ["lathe", "vessels"]),
                         ("human_lung", "Human Lung", "medium", ["lathe", "lobes"]),
                         ("human_tooth", "Human Tooth", "tiny", ["lathe", "subdivide"]),
     ]),
    ("geology", "Geology & Minerals", "crystal habits; facets must be planar",
     [
         ("quartz_crystal", "Quartz Crystal", "tiny", ["crystal", "prism", "subdivide"]),
         ("diamond", "Diamond", "micro", ["crystal", "brilliant_cut"]),
         ("amethyst_geode", "Amethyst Geode", "small", ["shell", "crystals", "cluster"]),
         ("pyramid", "Pyramid", "large", ["extrude_profile", "cone"]),
         ("rock", "Rock", "small", ["subdivide", "displace", "sphere"]),
         ("boulder", "Boulder", "large", ["subdivide", "displace", "sphere"]),
         ("volcano", "Volcano", "huge", ["cone", "crater", "subdivide"]),
         ("crystal_cluster", "Crystal Cluster", "small", ["crystal", "array", "cluster"]),
         ("salt_crystal", "Salt Crystal", "tiny", ["crystal", "cubic"]),
         ("obsidian_shard", "Obsidian Shard", "tiny", ["crystal", "prism"]),
         ("sand_dune", "Sand Dune", "large", ["subdivide", "displace"]),
                         ("glacier", "Glacier", "huge", ["subdivide", "extrude_profile"]),
                         ("cave_stalactite", "Stalactite", "medium", ["lathe", "cone"]),
                         ("cave_stalagmite", "Stalagmite", "medium", ["lathe", "cone"]),
                         ("fossil_ammonite", "Ammonite Fossil", "small", ["helix", "lathe"]),
                         ("meteorite", "Meteorite", "small", ["subdivide", "displace"]),
                         ("basalt_column", "Basalt Column", "large", ["cylinder", "array"]),
                         ("frozen_ice_cube", "Ice Cube", "small", ["box", "translucent"]),
     ]),
    ("nature", "Natural Elements & Weather", "no hard edges; simulation-flavoured",
     [
         ("cloud", "Cumulus Cloud", "large", ["cluster", "subdivide", "displace"]),
         ("rain_cloud", "Rain Cloud", "large", ["cluster", "rain", "subdivide"]),
         ("snow_cloud", "Snow Cloud", "large", ["cluster", "snow", "subdivide"]),
         ("lightning_bolt", "Lightning Bolt", "large", ["polyline", "subdivide"]),
         ("rainbow", "Rainbow", "huge", ["torus", "transparent"]),
         ("fire", "Campfire Flame", "small", ["flame", "emission", "subdivide"]),
         ("campfire", "Campfire", "medium", ["logs", "fire", "stones"]),
         ("smoke", "Smoke Plume", "large", ["cluster", "subdivide", "transparent"]),
         ("waterfall", "Waterfall", "huge", ["sheet", "foam", "subdivide"]),
         ("wave", "Ocean Wave", "large", ["subdivide", "displace", "foam"]),
         ("tornado", "Tornado", "huge", ["helix", "taper", "subdivide"]),
         ("snowflake", "Snowflake", "tiny", ["crystal", "arms", "array"]),
         ("raindrop", "Raindrop", "tiny", ["lathe", "subdivide"]),
         ("icicle", "Icicle", "small", ["cone", "lathe"]),
         ("dust_devil", "Dust Devil", "large", ["helix", "cluster"]),
         ("aurora", "Aurora", "huge", ["sheet", "emission", "subdivide"]),
         ("geyser", "Geyser", "large", ["jet", "column", "foam"]),
                         ("tide_pool", "Tide Pool", "medium", ["shell", "rocks", "water"]),
                         ("sandstorm", "Sandstorm", "huge", ["cloud", "particles", "subdivide"]),
     ]),
    ("space", "Astronomy & Space", "orbital geometry; scale cues must be explicit",
     [
         ("solar_system", "Solar System", "huge", ["orbits", "sphere", "rings"]),
         ("satellite", "Satellite", "small", ["rounded_box", "panel", "dish"]),
         ("space_station", "Space Station", "huge", ["modules", "solar_panels", "truss"]),
         ("rover", "Mars Rover", "medium", ["rounded_box", "wheels", "mast"]),
         ("telescope_array", "Radio Telescope", "huge", ["dish", "truss", "cylinder"]),
         ("planet_ringed", "Ringed Planet", "huge", ["sphere", "ring", "atmosphere"]),
         ("nebula", "Nebula", "huge", ["cluster", "emission", "subdivide"]),
         ("comet", "Comet", "medium", ["nucleus", "tail", "coma"]),
         ("meteor", "Meteor", "small", ["sphere", "tail", "emission"]),
         ("astronaut", "Astronaut", "large", ["human", "suit", "helmet"]),
         ("spacesuit_helmet", "Space Helmet", "small", ["sphere", "visor", "neck_ring"]),
         ("launch_rocket_pad", "Launch Pad", "huge", ["tower", "flame_trench", "platform"]),
         ("lunar_module", "Lunar Module", "large", ["rounded_box", "legs", "descent_stage"]),
         ("solar_panel_array", "Solar Panel Array", "large", ["panels", "truss", "frame"]),
                         ("black_hole", "Black Hole", "huge", ["accretion_disk", "lensing", "event_horizon"]),
                         ("crater", "Lunar Crater", "large", ["cone", "ring", "displace"]),
                         ("planet", "Planet", "huge", ["sphere", "atmosphere", "clouds"]),
                         ("probe", "Space Probe", "small", ["cylinder", "dish", "panel"]),
     ]),
    ("abstract", "Abstract & Geometric", "pure form; used as a control group",
     [
         ("cube", "Cube", "small", ["box", "bevel"]),
         ("sphere", "Sphere", "small", ["sphere"]),
         ("cone", "Cone", "small", ["cone"]),
         ("cylinder_shape", "Cylinder", "small", ["cylinder"]),
         ("torus_shape", "Torus", "small", ["torus"]),
         ("icosahedron", "Icosahedron", "small", ["sphere", "subdivide"]),
         ("dodecahedron", "Dodecahedron", "small", ["sphere", "subdivide"]),
         ("torus_knot", "Torus Knot", "small", ["helix", "tube"]),
                         ("mobius_strip", "Mobius Strip", "small", ["loft", "twist"]),
                         ("klein_bottle", "Klein Bottle", "small", ["lathe", "sphere", "twist"]),
                         ("spiral", "Spiral", "small", ["helix", "taper"]),
                         ("fractal_tree", "Fractal Tree", "medium", ["branch", "recursive"]),
                         ("space_filling", "Space Filling Curve", "medium", ["curve", "tube"]),
                         ("moebius_tower", "Tower", "medium", ["loft", "twist", "array"]),
                         ("gyroid", "Gyroid", "small", ["sphere", "subdivide", "boolean"]),
                         ("vase_modes", "Vase of Modes", "small", ["lathe", "curve"]),
                         ("superformula", "Superformula Solid", "small", ["lathe", "superformula"]),
     ]),
    ("gaming", "Gaming & Entertainment", "recognisable silhouettes, bold materials",
     [
         ("game_console", "Game Console", "medium", ["rounded_box", "box", "perforated_panel"]),
         ("handheld_console", "Handheld Console", "small", ["rounded_box", "button"]),
         ("arcade_cabinet", "Arcade Cabinet", "large", ["rounded_box", "extrude_profile", "screen"]),
         ("pinball_machine", "Pinball Machine", "large", ["rounded_box", "ramp", "cylinder"]),
         ("slot_machine", "Slot Machine", "large", ["rounded_box", "cylinder", "screen"]),
         ("dartboard", "Dartboard", "small", ["cylinder", "perforated_panel", "wire"]),
         ("dice_tower", "Dice Tower", "medium", ["extrude_profile", "box"]),
         ("playing_card", "Playing Card", "small", ["rounded_box", "bevel"]),
         ("chess_clock", "Chess Clock", "small", ["rounded_box", "dial"]),
         ("trophy", "Trophy", "medium", ["lathe", "arc_torus", "extrude_profile"]),
         ("medal", "Medal", "small", ["cylinder", "torus", "ribbon"]),
         ("poker_chip", "Poker Chip", "small", ["cylinder", "torus", "array"]),
         ("jigsaw_box", "Jigsaw Box", "large", ["rounded_box", "puzzle"]),
         ("music_box", "Music Box", "small", ["rounded_box", "lathe"]),
                         ("sewing_machine", "Sewing Machine", "medium", ["rounded_box", "wheel", "needle"]),
                         ("model_train_set", "Model Locomotive", "tiny", ["cylinder", "rounded_box", "wheels"]),
                         ("nerf_dart", "Foam Dart", "small", ["lathe", "fins", "cone"]),
                     ]),
    ("ritual", "Ritual & Cultural Objects", "symmetry, ornament, and intent",
     [
         ("totem_pole", "Totem Pole", "huge", ["cylinder", "carving", "array"]),
         ("moai", "Moai Statue", "huge", ["sculpt", "extruude_profile"]),
         ("ceremonial_mask", "Ceremonial Mask", "small", ["sculpt", "subdivide"]),
         ("incense_burner", "Incense Burner", "small", ["lathe", "perforated_panel"]),
         ("prayer_beads", "Prayer Beads", "tiny", ["sphere", "helix", "array"]),
         ("torii_gate", "Torii Gate", "huge", ["extrude_profile", "curve", "box"]),
         ("archery_bow", "Longbow", "large", ["curve", "extrude_profile", "string"]),
         ("frame_drum", "Frame Drum", "medium", ["cylinder", "lathe", "tension"]),
         ("sitar", "Sitar", "large", ["lathe", "extrude_profile", "tube"]),
                         ("handpan", "Handpan", "medium", ["lathe", "dome", "notes"]),
                         ("zen_garden_rock", "Garden Rock", "small", ["subdivide", "displace", "sphere"]),
                         ("incense_stick", "Incense Stick", "small", ["cylinder", "emission"]),
                         ("censer", "Censer", "small", ["lathe", "chain", "perforated_panel"]),
                         ("altar", "Altar Table", "large", ["rounded_box", "extrude_profile"]),
                         ("scroll", "Scroll", "medium", ["cylinder", "extrude_profile", "rolled"]),
                     ]),
    ("science_misc", "Everyday Technical Objects", "the long tail of designed things",
     [
         ("padlock_shackle", "Shackle", "small", ["arc_torus", "tube"]),
         ("hose_coupling", "Hose Coupling", "small", ["cylinder", "tube", "thread"]),
         ("cable_connector", "Cable Connector", "tiny", ["cylinder", "extrude_profile", "pins"]),
         ("usb_connector", "USB Plug", "tiny", ["extrude_profile", "box", "pins"]),
         ("cigarette_lighter", "Lighter", "small", ["extrude_profile", "cylinder", "wheel"]),
                         ("padlock_key", "Key", "small", ["extrude_profile", "bitting", "ring"]),
                         ("ruler", "Ruler", "medium", ["rounded_box", "ticks", "extrude_profile"]),
                         ("set_square", "Set Square", "small", ["extrude_profile", "hole"]),
                         ("protractor", "Protractor", "small", ["extrude_profile", "ticks"]),
                         ("compass_drawing", "Drawing Compass", "small", ["cylinder", "array", "hinge"]),
                         ("paperweight", "Paperweight", "small", ["sphere", "lathe", "glass"]),
                         ("bookend", "Bookend", "small", ["extrude_profile", "l_shape"]),
                         ("doorstop", "Doorstop Wedge", "small", ["extrude_profile", "wedge"]),
                         ("cable_tie", "Cable Tie", "tiny", ["ratchet", "notch", "tail"]),
                         ("picture_frame", "Picture Frame", "small", ["extrude_profile", "glass"]),
                         ("light_switch_double", "Double Light Switch", "small", ["rounded_box", "rocker"]),
                         ("door_stop", "Wall Stop", "tiny", ["cylinder", "torus", "rubber"]),
                         ("coathook", "Coat Hook", "tiny", ["arc_torus", "plate"]),
     ]),
]


def build():
    """Return the full catalog as plain data, ready for JSON."""
    items = []
    for dom_id, dom_title, note, rows in DOMAINS:
        for item_id, name, size, recipes in rows:
            lo, hi = SIZE[size]
            items.append(OrderedDict([
                ("id", item_id),
                ("name", name),
                ("domain", dom_id),
                ("domain_title", dom_title),
                ("size_class", size),
                ("size_mm", [lo, hi]),
                ("recipes", recipes),
                ("status", "todo"),
            ]))
    domains = [OrderedDict([("id", d[0]), ("name", d[1]), ("notes", d[2]),
                            ("count", len(d[3]))]) for d in DOMAINS]
    return OrderedDict([
        ("version", "1.0"),
        ("size_classes", OrderedDict((k, list(v)) for k, v in SIZE.items())),
        ("domains", domains),
        ("items", items),
    ])


if __name__ == "__main__":
    import json
    import os
    cat = build()
    out = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                       "catalog.json")
    with open(out, "w") as fh:
        json.dump(cat, fh, indent=1)
    print("wrote %s: %d domains, %d items"
          % (out, len(cat["domains"]), len(cat["items"])))